[package]
name = "portfolio"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
topcoat = { version = "0.9.0", features = [
  "icon-iconify",
  "tailwind",
  "font-fontsource",
] }

[build-dependencies]
topcoat = { version = "0.9.0", default-features = false, features = [
  "icon-iconify",
  "tailwind",
] }
